### PR TITLE
Capture process output in StanResults

### PR DESCRIPTION
**Pull request by epohlcibo**
Capture standard out and standard error streams from the CmdStan process so that calling routines can inspect it for later troubleshooting, etc. Addresses Issue #55

### CODE REVIEW

**Comment by ryan-richt** [comment]
Is there a reason this is still hanging out @epohlcibo?

**Comment by joewing** [comment]
I think we wanted to make this optional, so that it would be possible to see the output in real-time for debugging.

**Comment by joewing** [comment]
If we incorporated a logger into ScalaStan and just redirected the Stan output there, would that take care of this issue?  I think bringing a logger into the mix probably makes sense anyway.

**Comment by epohlcibo** [comment]
@joewing That works for me.

**Comment by joewing** [comment]
Closing since there's a logger now.

**Pull request closed without merging**
